// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module dut_dut_Pipeline_VITIS_LOOP_132_9_VITIS_LOOP_133_10 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RFIFONUM,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        dst_counter_8_reload,
        src_buff,
        dst_buff,
        skip_row_arr_address0,
        skip_row_arr_ce0,
        skip_row_arr_q0,
        icmp_ln31,
        select_ln63,
        dst_counter_11_out,
        dst_counter_11_out_ap_vld,
        grp_fu_1424_p_din0,
        grp_fu_1424_p_din1,
        grp_fu_1424_p_dout0,
        grp_fu_1424_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [63:0] m_axi_gmem_AWADDR;
output  [0:0] m_axi_gmem_AWID;
output  [31:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [0:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [7:0] m_axi_gmem_WDATA;
output  [0:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [0:0] m_axi_gmem_WID;
output  [0:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [63:0] m_axi_gmem_ARADDR;
output  [0:0] m_axi_gmem_ARID;
output  [31:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [0:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [7:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [0:0] m_axi_gmem_RID;
input  [10:0] m_axi_gmem_RFIFONUM;
input  [0:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [0:0] m_axi_gmem_BID;
input  [0:0] m_axi_gmem_BUSER;
input  [31:0] dst_counter_8_reload;
input  [63:0] src_buff;
input  [63:0] dst_buff;
output  [9:0] skip_row_arr_address0;
output   skip_row_arr_ce0;
input  [31:0] skip_row_arr_q0;
input  [0:0] icmp_ln31;
input  [6:0] select_ln63;
output  [31:0] dst_counter_11_out;
output   dst_counter_11_out_ap_vld;
output  [31:0] grp_fu_1424_p_din0;
output  [4:0] grp_fu_1424_p_din1;
input  [31:0] grp_fu_1424_p_dout0;
output   grp_fu_1424_p_ce;

reg ap_idle;
reg m_axi_gmem_AWVALID;
reg m_axi_gmem_WVALID;
reg m_axi_gmem_ARVALID;
reg m_axi_gmem_RREADY;
reg m_axi_gmem_BREADY;
reg skip_row_arr_ce0;
reg dst_counter_11_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_enable_reg_pp0_iter19;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_state11_pp0_stage0_iter10;
wire    ap_block_state12_pp0_stage0_iter11;
wire    ap_block_state13_pp0_stage0_iter12;
reg    ap_block_state14_pp0_stage0_iter13;
wire    ap_block_state15_pp0_stage0_iter14;
wire    ap_block_state16_pp0_stage0_iter15;
wire    ap_block_state17_pp0_stage0_iter16;
wire    ap_block_state18_pp0_stage0_iter17;
wire    ap_block_state19_pp0_stage0_iter18;
reg    ap_block_state20_pp0_stage0_iter19;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln132_fu_228_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem_blk_n_AR;
wire    ap_block_pp0_stage0;
reg    gmem_blk_n_R;
reg    gmem_blk_n_AW;
reg    gmem_blk_n_W;
reg    gmem_blk_n_B;
reg    ap_block_pp0_stage0_11001;
wire   [31:0] select_ln63_cast_fu_196_p1;
reg   [31:0] select_ln63_cast_reg_470;
reg   [0:0] icmp_ln132_reg_475;
reg   [0:0] icmp_ln132_reg_475_pp0_iter2_reg;
reg   [0:0] icmp_ln132_reg_475_pp0_iter3_reg;
reg   [0:0] icmp_ln132_reg_475_pp0_iter4_reg;
reg   [0:0] icmp_ln132_reg_475_pp0_iter5_reg;
reg   [0:0] icmp_ln132_reg_475_pp0_iter6_reg;
reg   [0:0] icmp_ln132_reg_475_pp0_iter7_reg;
reg   [0:0] icmp_ln132_reg_475_pp0_iter8_reg;
reg   [0:0] icmp_ln132_reg_475_pp0_iter9_reg;
reg   [0:0] icmp_ln132_reg_475_pp0_iter10_reg;
reg   [0:0] icmp_ln132_reg_475_pp0_iter11_reg;
reg   [0:0] icmp_ln132_reg_475_pp0_iter12_reg;
reg   [0:0] icmp_ln132_reg_475_pp0_iter13_reg;
reg   [0:0] icmp_ln132_reg_475_pp0_iter14_reg;
reg   [0:0] icmp_ln132_reg_475_pp0_iter15_reg;
reg   [0:0] icmp_ln132_reg_475_pp0_iter16_reg;
reg   [0:0] icmp_ln132_reg_475_pp0_iter17_reg;
wire   [3:0] select_ln132_fu_252_p3;
reg   [3:0] select_ln132_reg_479;
reg   [3:0] select_ln132_reg_479_pp0_iter2_reg;
reg   [3:0] select_ln132_reg_479_pp0_iter3_reg;
reg   [3:0] select_ln132_reg_479_pp0_iter4_reg;
wire   [0:0] icmp_ln135_fu_260_p2;
reg   [0:0] icmp_ln135_reg_484;
reg   [0:0] icmp_ln135_reg_484_pp0_iter2_reg;
reg   [0:0] icmp_ln135_reg_484_pp0_iter3_reg;
reg   [0:0] icmp_ln135_reg_484_pp0_iter4_reg;
reg  signed [31:0] skip_row_arr_load_reg_495;
reg   [31:0] mul_ln137_reg_500;
reg   [63:0] gmem_addr_reg_505;
reg   [63:0] gmem_addr_5_reg_511;
reg   [63:0] gmem_addr_5_reg_511_pp0_iter6_reg;
reg   [63:0] gmem_addr_5_reg_511_pp0_iter7_reg;
reg   [63:0] gmem_addr_5_reg_511_pp0_iter8_reg;
reg   [63:0] gmem_addr_5_reg_511_pp0_iter9_reg;
reg   [63:0] gmem_addr_5_reg_511_pp0_iter10_reg;
reg   [63:0] gmem_addr_5_reg_511_pp0_iter11_reg;
reg   [63:0] gmem_addr_5_reg_511_pp0_iter12_reg;
reg   [7:0] gmem_addr_read_reg_517;
wire   [63:0] zext_ln137_fu_266_p1;
wire   [63:0] add_ln134_1_fu_336_p2;
wire   [63:0] add_ln134_3_fu_357_p2;
reg    ap_block_pp0_stage0_01001;
reg   [3:0] j_4_fu_98;
wire   [3:0] j_fu_285_p2;
wire    ap_loop_init;
reg   [31:0] dst_counter_11_fu_102;
wire   [31:0] dst_counter_fu_391_p3;
reg   [31:0] src_counter_fu_106;
wire   [31:0] src_counter_17_fu_398_p3;
reg   [31:0] counter_fu_110;
wire   [31:0] counter_12_fu_277_p3;
reg   [12:0] indvar_flatten112_fu_114;
wire   [12:0] add_ln132_fu_234_p2;
wire   [0:0] icmp_ln133_fu_246_p2;
wire   [31:0] counter_11_fu_271_p2;
wire   [31:0] add_ln134_fu_320_p2;
wire   [31:0] j_4_cast_fu_317_p1;
wire   [31:0] sub_ln134_fu_326_p2;
wire   [63:0] zext_ln134_fu_332_p1;
wire   [31:0] add_ln134_2_fu_347_p2;
wire   [63:0] zext_ln134_1_fu_353_p1;
wire   [31:0] src_counter_14_fu_368_p2;
wire   [31:0] src_counter_15_fu_373_p3;
wire   [31:0] dst_counter_12_fu_385_p2;
wire   [31:0] src_counter_16_fu_380_p2;
reg    grp_fu_306_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg    ap_loop_exit_ready_pp0_iter15_reg;
reg    ap_loop_exit_ready_pp0_iter16_reg;
reg    ap_loop_exit_ready_pp0_iter17_reg;
reg    ap_loop_exit_ready_pp0_iter18_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_enable_reg_pp0_iter19 = 1'b0;
#0 ap_done_reg = 1'b0;
end

dut_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter18_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter19 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            counter_fu_110 <= 32'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln132_fu_228_p2 == 1'd0))) begin
            counter_fu_110 <= counter_12_fu_277_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            dst_counter_11_fu_102 <= dst_counter_8_reload;
        end else if ((ap_enable_reg_pp0_iter5 == 1'b1)) begin
            dst_counter_11_fu_102 <= dst_counter_fu_391_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten112_fu_114 <= 13'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln132_fu_228_p2 == 1'd0))) begin
            indvar_flatten112_fu_114 <= add_ln132_fu_234_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            j_4_fu_98 <= 4'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln132_fu_228_p2 == 1'd0))) begin
            j_4_fu_98 <= j_fu_285_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            src_counter_fu_106 <= 32'd33;
        end else if ((ap_enable_reg_pp0_iter5 == 1'b1)) begin
            src_counter_fu_106 <= src_counter_17_fu_398_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
        ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
        ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
        ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
        ap_loop_exit_ready_pp0_iter18_reg <= ap_loop_exit_ready_pp0_iter17_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        gmem_addr_5_reg_511 <= add_ln134_3_fu_357_p2;
        gmem_addr_5_reg_511_pp0_iter10_reg <= gmem_addr_5_reg_511_pp0_iter9_reg;
        gmem_addr_5_reg_511_pp0_iter11_reg <= gmem_addr_5_reg_511_pp0_iter10_reg;
        gmem_addr_5_reg_511_pp0_iter12_reg <= gmem_addr_5_reg_511_pp0_iter11_reg;
        gmem_addr_5_reg_511_pp0_iter6_reg <= gmem_addr_5_reg_511;
        gmem_addr_5_reg_511_pp0_iter7_reg <= gmem_addr_5_reg_511_pp0_iter6_reg;
        gmem_addr_5_reg_511_pp0_iter8_reg <= gmem_addr_5_reg_511_pp0_iter7_reg;
        gmem_addr_5_reg_511_pp0_iter9_reg <= gmem_addr_5_reg_511_pp0_iter8_reg;
        gmem_addr_read_reg_517 <= m_axi_gmem_RDATA;
        gmem_addr_reg_505 <= add_ln134_1_fu_336_p2;
        icmp_ln132_reg_475_pp0_iter10_reg <= icmp_ln132_reg_475_pp0_iter9_reg;
        icmp_ln132_reg_475_pp0_iter11_reg <= icmp_ln132_reg_475_pp0_iter10_reg;
        icmp_ln132_reg_475_pp0_iter12_reg <= icmp_ln132_reg_475_pp0_iter11_reg;
        icmp_ln132_reg_475_pp0_iter13_reg <= icmp_ln132_reg_475_pp0_iter12_reg;
        icmp_ln132_reg_475_pp0_iter14_reg <= icmp_ln132_reg_475_pp0_iter13_reg;
        icmp_ln132_reg_475_pp0_iter15_reg <= icmp_ln132_reg_475_pp0_iter14_reg;
        icmp_ln132_reg_475_pp0_iter16_reg <= icmp_ln132_reg_475_pp0_iter15_reg;
        icmp_ln132_reg_475_pp0_iter17_reg <= icmp_ln132_reg_475_pp0_iter16_reg;
        icmp_ln132_reg_475_pp0_iter2_reg <= icmp_ln132_reg_475;
        icmp_ln132_reg_475_pp0_iter3_reg <= icmp_ln132_reg_475_pp0_iter2_reg;
        icmp_ln132_reg_475_pp0_iter4_reg <= icmp_ln132_reg_475_pp0_iter3_reg;
        icmp_ln132_reg_475_pp0_iter5_reg <= icmp_ln132_reg_475_pp0_iter4_reg;
        icmp_ln132_reg_475_pp0_iter6_reg <= icmp_ln132_reg_475_pp0_iter5_reg;
        icmp_ln132_reg_475_pp0_iter7_reg <= icmp_ln132_reg_475_pp0_iter6_reg;
        icmp_ln132_reg_475_pp0_iter8_reg <= icmp_ln132_reg_475_pp0_iter7_reg;
        icmp_ln132_reg_475_pp0_iter9_reg <= icmp_ln132_reg_475_pp0_iter8_reg;
        icmp_ln135_reg_484_pp0_iter2_reg <= icmp_ln135_reg_484;
        icmp_ln135_reg_484_pp0_iter3_reg <= icmp_ln135_reg_484_pp0_iter2_reg;
        icmp_ln135_reg_484_pp0_iter4_reg <= icmp_ln135_reg_484_pp0_iter3_reg;
        select_ln132_reg_479_pp0_iter2_reg <= select_ln132_reg_479;
        select_ln132_reg_479_pp0_iter3_reg <= select_ln132_reg_479_pp0_iter2_reg;
        select_ln132_reg_479_pp0_iter4_reg <= select_ln132_reg_479_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        icmp_ln132_reg_475 <= icmp_ln132_fu_228_p2;
        select_ln63_cast_reg_470[6 : 0] <= select_ln63_cast_fu_196_p1[6 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln132_fu_228_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln135_reg_484 <= icmp_ln135_fu_260_p2;
        select_ln132_reg_479 <= select_ln132_fu_252_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln135_reg_484_pp0_iter3_reg == 1'd1) & (icmp_ln31 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        mul_ln137_reg_500 <= grp_fu_1424_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln31 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        skip_row_arr_load_reg_495 <= skip_row_arr_q0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln132_fu_228_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter18_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln132_reg_475_pp0_iter17_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        dst_counter_11_out_ap_vld = 1'b1;
    end else begin
        dst_counter_11_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        gmem_blk_n_AR = m_axi_gmem_ARREADY;
    end else begin
        gmem_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        gmem_blk_n_AW = m_axi_gmem_AWREADY;
    end else begin
        gmem_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter19 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        gmem_blk_n_B = m_axi_gmem_BVALID;
    end else begin
        gmem_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        gmem_blk_n_R = m_axi_gmem_RVALID;
    end else begin
        gmem_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        gmem_blk_n_W = m_axi_gmem_WREADY;
    end else begin
        gmem_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_306_ce = 1'b1;
    end else begin
        grp_fu_306_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_gmem_ARVALID = 1'b1;
    end else begin
        m_axi_gmem_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_gmem_AWVALID = 1'b1;
    end else begin
        m_axi_gmem_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter19 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_gmem_BREADY = 1'b1;
    end else begin
        m_axi_gmem_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_gmem_RREADY = 1'b1;
    end else begin
        m_axi_gmem_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_gmem_WVALID = 1'b1;
    end else begin
        m_axi_gmem_WVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        skip_row_arr_ce0 = 1'b1;
    end else begin
        skip_row_arr_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln132_fu_234_p2 = (indvar_flatten112_fu_114 + 13'd1);

assign add_ln134_1_fu_336_p2 = (zext_ln134_fu_332_p1 + src_buff);

assign add_ln134_2_fu_347_p2 = (j_4_cast_fu_317_p1 + dst_counter_11_fu_102);

assign add_ln134_3_fu_357_p2 = (zext_ln134_1_fu_353_p1 + dst_buff);

assign add_ln134_fu_320_p2 = (src_counter_fu_106 + 32'd10);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter19 == 1'b1) & (m_axi_gmem_BVALID == 1'b0)) | ((ap_enable_reg_pp0_iter13 == 1'b1) & (m_axi_gmem_RVALID == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter19 == 1'b1) & (m_axi_gmem_BVALID == 1'b0)) | ((ap_enable_reg_pp0_iter14 == 1'b1) & (m_axi_gmem_WREADY == 1'b0)) | ((ap_enable_reg_pp0_iter13 == 1'b1) & ((m_axi_gmem_AWREADY == 1'b0) | (m_axi_gmem_RVALID == 1'b0))) | ((ap_enable_reg_pp0_iter6 == 1'b1) & (m_axi_gmem_ARREADY == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter19 == 1'b1) & (m_axi_gmem_BVALID == 1'b0)) | ((ap_enable_reg_pp0_iter14 == 1'b1) & (m_axi_gmem_WREADY == 1'b0)) | ((ap_enable_reg_pp0_iter13 == 1'b1) & ((m_axi_gmem_AWREADY == 1'b0) | (m_axi_gmem_RVALID == 1'b0))) | ((ap_enable_reg_pp0_iter6 == 1'b1) & (m_axi_gmem_ARREADY == 1'b0)));
end

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state14_pp0_stage0_iter13 = (m_axi_gmem_RVALID == 1'b0);
end

assign ap_block_state15_pp0_stage0_iter14 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage0_iter15 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter16 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage0_iter17 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage0_iter18 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state20_pp0_stage0_iter19 = (m_axi_gmem_BVALID == 1'b0);
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign counter_11_fu_271_p2 = (counter_fu_110 + 32'd1);

assign counter_12_fu_277_p3 = ((icmp_ln135_fu_260_p2[0:0] == 1'b1) ? counter_11_fu_271_p2 : counter_fu_110);

assign dst_counter_11_out = dst_counter_11_fu_102;

assign dst_counter_12_fu_385_p2 = (dst_counter_11_fu_102 + 32'd8);

assign dst_counter_fu_391_p3 = ((icmp_ln135_reg_484_pp0_iter4_reg[0:0] == 1'b1) ? dst_counter_12_fu_385_p2 : dst_counter_11_fu_102);

assign grp_fu_1424_p_ce = grp_fu_306_ce;

assign grp_fu_1424_p_din0 = skip_row_arr_load_reg_495;

assign grp_fu_1424_p_din1 = 32'd11;

assign icmp_ln132_fu_228_p2 = ((indvar_flatten112_fu_114 == 13'd8000) ? 1'b1 : 1'b0);

assign icmp_ln133_fu_246_p2 = ((j_4_fu_98 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln135_fu_260_p2 = ((select_ln132_fu_252_p3 == 4'd7) ? 1'b1 : 1'b0);

assign j_4_cast_fu_317_p1 = select_ln132_reg_479_pp0_iter4_reg;

assign j_fu_285_p2 = (select_ln132_fu_252_p3 + 4'd1);

assign m_axi_gmem_ARADDR = gmem_addr_reg_505;

assign m_axi_gmem_ARBURST = 2'd0;

assign m_axi_gmem_ARCACHE = 4'd0;

assign m_axi_gmem_ARID = 1'd0;

assign m_axi_gmem_ARLEN = 32'd1;

assign m_axi_gmem_ARLOCK = 2'd0;

assign m_axi_gmem_ARPROT = 3'd0;

assign m_axi_gmem_ARQOS = 4'd0;

assign m_axi_gmem_ARREGION = 4'd0;

assign m_axi_gmem_ARSIZE = 3'd0;

assign m_axi_gmem_ARUSER = 1'd0;

assign m_axi_gmem_AWADDR = gmem_addr_5_reg_511_pp0_iter12_reg;

assign m_axi_gmem_AWBURST = 2'd0;

assign m_axi_gmem_AWCACHE = 4'd0;

assign m_axi_gmem_AWID = 1'd0;

assign m_axi_gmem_AWLEN = 32'd1;

assign m_axi_gmem_AWLOCK = 2'd0;

assign m_axi_gmem_AWPROT = 3'd0;

assign m_axi_gmem_AWQOS = 4'd0;

assign m_axi_gmem_AWREGION = 4'd0;

assign m_axi_gmem_AWSIZE = 3'd0;

assign m_axi_gmem_AWUSER = 1'd0;

assign m_axi_gmem_WDATA = gmem_addr_read_reg_517;

assign m_axi_gmem_WID = 1'd0;

assign m_axi_gmem_WLAST = 1'b0;

assign m_axi_gmem_WSTRB = 1'd1;

assign m_axi_gmem_WUSER = 1'd0;

assign select_ln132_fu_252_p3 = ((icmp_ln133_fu_246_p2[0:0] == 1'b1) ? 4'd0 : j_4_fu_98);

assign select_ln63_cast_fu_196_p1 = select_ln63;

assign skip_row_arr_address0 = zext_ln137_fu_266_p1;

assign src_counter_14_fu_368_p2 = (mul_ln137_reg_500 + src_counter_fu_106);

assign src_counter_15_fu_373_p3 = ((icmp_ln31[0:0] == 1'b1) ? src_counter_14_fu_368_p2 : src_counter_fu_106);

assign src_counter_16_fu_380_p2 = (src_counter_15_fu_373_p3 + select_ln63_cast_reg_470);

assign src_counter_17_fu_398_p3 = ((icmp_ln135_reg_484_pp0_iter4_reg[0:0] == 1'b1) ? src_counter_16_fu_380_p2 : src_counter_fu_106);

assign sub_ln134_fu_326_p2 = (add_ln134_fu_320_p2 - j_4_cast_fu_317_p1);

assign zext_ln134_1_fu_353_p1 = add_ln134_2_fu_347_p2;

assign zext_ln134_fu_332_p1 = sub_ln134_fu_326_p2;

assign zext_ln137_fu_266_p1 = counter_fu_110;

always @ (posedge ap_clk) begin
    select_ln63_cast_reg_470[31:7] <= 25'b0000000000000000000000000;
end

endmodule //dut_dut_Pipeline_VITIS_LOOP_132_9_VITIS_LOOP_133_10
