############################################################
## This file is generated automatically by Vitis HLS.
## Please DO NOT edit it.
## Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
############################################################
set_directive_top -name canny "canny"
set_directive_pipeline "canny/NonMaxSup_y"
set_directive_unroll "canny/gradient_theta_shift"
set_directive_unroll "canny/canny_label0"
set_directive_unroll "canny/canny_label1"
set_directive_unroll "canny/canny_label2"
set_directive_unroll "canny/canny_label3"
set_directive_unroll "canny/canny_label4"
set_directive_unroll "canny/canny_label5"
set_directive_unroll "canny/canny_label6"
set_directive_unroll "canny/canny_label7"
set_directive_unroll "canny/canny_label8"
set_directive_unroll "canny/canny_label9"
set_directive_unroll "canny/canny_label10"
set_directive_unroll "canny/canny_label11"
set_directive_unroll "canny/canny_label12"
set_directive_unroll "canny/canny_label13"
set_directive_unroll "canny/canny_label14"
set_directive_unroll "canny/canny_label15"
set_directive_unroll "canny/canny_label16"
set_directive_unroll "canny/canny_label17"
set_directive_unroll "canny/canny_label18"
set_directive_unroll "canny/canny_label19"
set_directive_unroll "canny/canny_label20"
set_directive_unroll "canny/canny_label21"
set_directive_unroll "canny/canny_label22"
set_directive_unroll "canny/canny_label23"
set_directive_unroll "canny/canny_label24"
set_directive_unroll "canny/canny_label25"
set_directive_unroll "canny/canny_label26"
set_directive_unroll "canny/canny_label27"
set_directive_unroll "canny/canny_label28"
set_directive_unroll "canny/canny_label29"
set_directive_unroll "canny/canny_label30"
set_directive_unroll "canny/canny_label31"
set_directive_unroll "canny/canny_label32"
set_directive_unroll "canny/canny_label33"
set_directive_unroll "canny/canny_label34"
set_directive_unroll "canny/canny_label35"
set_directive_unroll "canny/canny_label36"
set_directive_unroll "canny/canny_label37"
set_directive_unroll "canny/canny_label38"
set_directive_unroll "canny/canny_label39"
set_directive_unroll "canny/canny_label40"
set_directive_unroll "canny/canny_label41"
