// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module dut_dut_Pipeline_VITIS_LOOP_88_5_VITIS_LOOP_89_6 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RFIFONUM,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        dst_counter_1_reload,
        skip_row_arr_address0,
        skip_row_arr_ce0,
        skip_row_arr_q0,
        icmp_ln31,
        select_ln63,
        dst_buff,
        src_buff,
        dst_counter_4_out,
        dst_counter_4_out_ap_vld,
        grp_fu_1424_p_din0,
        grp_fu_1424_p_din1,
        grp_fu_1424_p_dout0,
        grp_fu_1424_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [63:0] m_axi_gmem_AWADDR;
output  [0:0] m_axi_gmem_AWID;
output  [31:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [0:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [7:0] m_axi_gmem_WDATA;
output  [0:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [0:0] m_axi_gmem_WID;
output  [0:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [63:0] m_axi_gmem_ARADDR;
output  [0:0] m_axi_gmem_ARID;
output  [31:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [0:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [7:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [0:0] m_axi_gmem_RID;
input  [10:0] m_axi_gmem_RFIFONUM;
input  [0:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [0:0] m_axi_gmem_BID;
input  [0:0] m_axi_gmem_BUSER;
input  [31:0] dst_counter_1_reload;
output  [9:0] skip_row_arr_address0;
output   skip_row_arr_ce0;
input  [31:0] skip_row_arr_q0;
input  [0:0] icmp_ln31;
input  [6:0] select_ln63;
input  [63:0] dst_buff;
input  [63:0] src_buff;
output  [31:0] dst_counter_4_out;
output   dst_counter_4_out_ap_vld;
output  [31:0] grp_fu_1424_p_din0;
output  [4:0] grp_fu_1424_p_din1;
input  [31:0] grp_fu_1424_p_dout0;
output   grp_fu_1424_p_ce;

reg ap_idle;
reg m_axi_gmem_AWVALID;
reg m_axi_gmem_WVALID;
reg m_axi_gmem_ARVALID;
reg m_axi_gmem_RREADY;
reg m_axi_gmem_BREADY;
reg skip_row_arr_ce0;
reg dst_counter_4_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_enable_reg_pp0_iter19;
reg    ap_enable_reg_pp0_iter20;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
reg   [0:0] icmp_ln88_reg_495;
reg   [0:0] icmp_ln88_reg_495_pp0_iter5_reg;
reg   [0:0] icmp_ln90_reg_504;
reg   [0:0] icmp_ln90_reg_504_pp0_iter5_reg;
reg    ap_predicate_op77_readreq_state7;
reg    ap_block_state7_io;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_state11_pp0_stage0_iter10;
wire    ap_block_state12_pp0_stage0_iter11;
wire    ap_block_state13_pp0_stage0_iter12;
reg   [0:0] icmp_ln88_reg_495_pp0_iter12_reg;
reg   [0:0] icmp_ln90_reg_504_pp0_iter12_reg;
reg    ap_predicate_op94_read_state14;
reg    ap_block_state14_pp0_stage0_iter13;
wire    ap_block_state15_pp0_stage0_iter14;
wire    ap_block_state16_pp0_stage0_iter15;
wire    ap_block_state17_pp0_stage0_iter16;
wire    ap_block_state18_pp0_stage0_iter17;
wire    ap_block_state19_pp0_stage0_iter18;
wire    ap_block_state20_pp0_stage0_iter19;
reg    ap_block_state21_pp0_stage0_iter20;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln88_fu_240_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem_blk_n_AW;
wire    ap_block_pp0_stage0;
reg    gmem_blk_n_W;
reg    gmem_blk_n_B;
reg    gmem_blk_n_AR;
reg    gmem_blk_n_R;
reg    ap_block_pp0_stage0_11001;
wire   [31:0] select_ln63_cast_fu_208_p1;
reg   [31:0] select_ln63_cast_reg_490;
reg   [0:0] icmp_ln88_reg_495_pp0_iter2_reg;
reg   [0:0] icmp_ln88_reg_495_pp0_iter3_reg;
reg   [0:0] icmp_ln88_reg_495_pp0_iter4_reg;
reg   [0:0] icmp_ln88_reg_495_pp0_iter6_reg;
reg   [0:0] icmp_ln88_reg_495_pp0_iter7_reg;
reg   [0:0] icmp_ln88_reg_495_pp0_iter8_reg;
reg   [0:0] icmp_ln88_reg_495_pp0_iter9_reg;
reg   [0:0] icmp_ln88_reg_495_pp0_iter10_reg;
reg   [0:0] icmp_ln88_reg_495_pp0_iter11_reg;
reg   [0:0] icmp_ln88_reg_495_pp0_iter13_reg;
reg   [0:0] icmp_ln88_reg_495_pp0_iter14_reg;
reg   [0:0] icmp_ln88_reg_495_pp0_iter15_reg;
reg   [0:0] icmp_ln88_reg_495_pp0_iter16_reg;
reg   [0:0] icmp_ln88_reg_495_pp0_iter17_reg;
reg   [0:0] icmp_ln88_reg_495_pp0_iter18_reg;
wire   [3:0] select_ln88_fu_261_p3;
reg   [3:0] select_ln88_reg_499;
reg   [3:0] select_ln88_reg_499_pp0_iter2_reg;
reg   [3:0] select_ln88_reg_499_pp0_iter3_reg;
reg   [3:0] select_ln88_reg_499_pp0_iter4_reg;
reg   [3:0] select_ln88_reg_499_pp0_iter5_reg;
reg   [3:0] select_ln88_reg_499_pp0_iter6_reg;
reg   [3:0] select_ln88_reg_499_pp0_iter7_reg;
reg   [3:0] select_ln88_reg_499_pp0_iter8_reg;
reg   [3:0] select_ln88_reg_499_pp0_iter9_reg;
reg   [3:0] select_ln88_reg_499_pp0_iter10_reg;
reg   [3:0] select_ln88_reg_499_pp0_iter11_reg;
reg   [3:0] select_ln88_reg_499_pp0_iter12_reg;
wire   [0:0] icmp_ln90_fu_269_p2;
reg   [0:0] icmp_ln90_reg_504_pp0_iter2_reg;
reg   [0:0] icmp_ln90_reg_504_pp0_iter3_reg;
reg   [0:0] icmp_ln90_reg_504_pp0_iter4_reg;
reg   [0:0] icmp_ln90_reg_504_pp0_iter6_reg;
reg   [0:0] icmp_ln90_reg_504_pp0_iter7_reg;
reg   [0:0] icmp_ln90_reg_504_pp0_iter8_reg;
reg   [0:0] icmp_ln90_reg_504_pp0_iter9_reg;
reg   [0:0] icmp_ln90_reg_504_pp0_iter10_reg;
reg   [0:0] icmp_ln90_reg_504_pp0_iter11_reg;
reg   [0:0] icmp_ln90_reg_504_pp0_iter13_reg;
wire   [0:0] icmp_ln95_fu_278_p2;
reg   [0:0] icmp_ln95_reg_508;
reg   [0:0] icmp_ln95_reg_508_pp0_iter2_reg;
reg   [0:0] icmp_ln95_reg_508_pp0_iter3_reg;
reg   [0:0] icmp_ln95_reg_508_pp0_iter4_reg;
reg   [0:0] icmp_ln95_reg_508_pp0_iter5_reg;
reg   [0:0] icmp_ln95_reg_508_pp0_iter6_reg;
reg   [0:0] icmp_ln95_reg_508_pp0_iter7_reg;
reg   [0:0] icmp_ln95_reg_508_pp0_iter8_reg;
reg   [0:0] icmp_ln95_reg_508_pp0_iter9_reg;
reg   [0:0] icmp_ln95_reg_508_pp0_iter10_reg;
reg   [0:0] icmp_ln95_reg_508_pp0_iter11_reg;
reg   [0:0] icmp_ln95_reg_508_pp0_iter12_reg;
reg  signed [31:0] skip_row_arr_load_reg_519;
reg   [31:0] mul_ln97_reg_524;
reg   [63:0] gmem_addr_1_reg_529;
reg   [63:0] gmem_addr_reg_535;
reg   [7:0] gmem_addr_1_read_reg_541;
wire   [7:0] ap_phi_reg_pp0_iter0_storemerge_reg_196;
reg   [7:0] ap_phi_reg_pp0_iter1_storemerge_reg_196;
reg   [7:0] ap_phi_reg_pp0_iter2_storemerge_reg_196;
reg   [7:0] ap_phi_reg_pp0_iter3_storemerge_reg_196;
reg   [7:0] ap_phi_reg_pp0_iter4_storemerge_reg_196;
reg   [7:0] ap_phi_reg_pp0_iter5_storemerge_reg_196;
reg   [7:0] ap_phi_reg_pp0_iter6_storemerge_reg_196;
reg   [7:0] ap_phi_reg_pp0_iter7_storemerge_reg_196;
reg   [7:0] ap_phi_reg_pp0_iter8_storemerge_reg_196;
reg   [7:0] ap_phi_reg_pp0_iter9_storemerge_reg_196;
reg   [7:0] ap_phi_reg_pp0_iter10_storemerge_reg_196;
reg   [7:0] ap_phi_reg_pp0_iter11_storemerge_reg_196;
reg   [7:0] ap_phi_reg_pp0_iter12_storemerge_reg_196;
reg   [7:0] ap_phi_reg_pp0_iter13_storemerge_reg_196;
reg   [7:0] ap_phi_reg_pp0_iter14_storemerge_reg_196;
reg   [7:0] ap_phi_reg_pp0_iter15_storemerge_reg_196;
wire   [63:0] zext_ln97_fu_284_p1;
wire   [63:0] add_ln91_3_fu_342_p2;
wire   [63:0] add_ln91_1_fu_401_p2;
reg    ap_block_pp0_stage0_01001;
reg   [3:0] j_fu_98;
wire   [3:0] j_1_fu_303_p2;
wire    ap_loop_init;
reg   [31:0] dst_counter_fu_102;
wire   [31:0] dst_counter_3_fu_421_p3;
reg   [31:0] src_counter_fu_106;
wire   [31:0] src_counter_5_fu_373_p3;
reg   [31:0] counter_fu_110;
wire   [31:0] counter_3_fu_295_p3;
reg   [12:0] indvar_flatten98_fu_114;
wire   [12:0] add_ln88_fu_246_p2;
wire   [0:0] icmp_ln89_fu_255_p2;
wire   [31:0] counter_2_fu_289_p2;
wire   [31:0] add_ln91_2_fu_332_p2;
wire   [63:0] zext_ln91_1_fu_338_p1;
wire   [31:0] src_counter_2_fu_356_p2;
wire   [31:0] src_counter_3_fu_361_p3;
wire   [31:0] src_counter_4_fu_368_p2;
wire   [31:0] j_1_cast_fu_388_p1;
wire   [31:0] add_ln91_fu_391_p2;
wire   [63:0] zext_ln91_fu_397_p1;
wire   [31:0] dst_counter_2_fu_415_p2;
reg    grp_fu_324_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg    ap_loop_exit_ready_pp0_iter15_reg;
reg    ap_loop_exit_ready_pp0_iter16_reg;
reg    ap_loop_exit_ready_pp0_iter17_reg;
reg    ap_loop_exit_ready_pp0_iter18_reg;
reg    ap_loop_exit_ready_pp0_iter19_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_425;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_enable_reg_pp0_iter19 = 1'b0;
#0 ap_enable_reg_pp0_iter20 = 1'b0;
#0 ap_done_reg = 1'b0;
end

dut_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter19_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter19 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter20 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((icmp_ln90_reg_504_pp0_iter13_reg == 1'd1) & (icmp_ln88_reg_495_pp0_iter13_reg == 1'd0))) begin
            ap_phi_reg_pp0_iter15_storemerge_reg_196 <= gmem_addr_1_read_reg_541;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter15_storemerge_reg_196 <= ap_phi_reg_pp0_iter14_storemerge_reg_196;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_425)) begin
        if (((icmp_ln90_fu_269_p2 == 1'd0) & (icmp_ln88_fu_240_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_storemerge_reg_196 <= 8'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_storemerge_reg_196 <= ap_phi_reg_pp0_iter1_storemerge_reg_196;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            counter_fu_110 <= 32'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln88_fu_240_p2 == 1'd0))) begin
            counter_fu_110 <= counter_3_fu_295_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            dst_counter_fu_102 <= dst_counter_1_reload;
        end else if ((ap_enable_reg_pp0_iter13 == 1'b1)) begin
            dst_counter_fu_102 <= dst_counter_3_fu_421_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten98_fu_114 <= 13'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln88_fu_240_p2 == 1'd0))) begin
            indvar_flatten98_fu_114 <= add_ln88_fu_246_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            j_fu_98 <= 4'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln88_fu_240_p2 == 1'd0))) begin
            j_fu_98 <= j_1_fu_303_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            src_counter_fu_106 <= 32'd11;
        end else if ((ap_enable_reg_pp0_iter5 == 1'b1)) begin
            src_counter_fu_106 <= src_counter_5_fu_373_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
        ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
        ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
        ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
        ap_loop_exit_ready_pp0_iter18_reg <= ap_loop_exit_ready_pp0_iter17_reg;
        ap_loop_exit_ready_pp0_iter19_reg <= ap_loop_exit_ready_pp0_iter18_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        icmp_ln88_reg_495_pp0_iter10_reg <= icmp_ln88_reg_495_pp0_iter9_reg;
        icmp_ln88_reg_495_pp0_iter11_reg <= icmp_ln88_reg_495_pp0_iter10_reg;
        icmp_ln88_reg_495_pp0_iter12_reg <= icmp_ln88_reg_495_pp0_iter11_reg;
        icmp_ln88_reg_495_pp0_iter13_reg <= icmp_ln88_reg_495_pp0_iter12_reg;
        icmp_ln88_reg_495_pp0_iter14_reg <= icmp_ln88_reg_495_pp0_iter13_reg;
        icmp_ln88_reg_495_pp0_iter15_reg <= icmp_ln88_reg_495_pp0_iter14_reg;
        icmp_ln88_reg_495_pp0_iter16_reg <= icmp_ln88_reg_495_pp0_iter15_reg;
        icmp_ln88_reg_495_pp0_iter17_reg <= icmp_ln88_reg_495_pp0_iter16_reg;
        icmp_ln88_reg_495_pp0_iter18_reg <= icmp_ln88_reg_495_pp0_iter17_reg;
        icmp_ln88_reg_495_pp0_iter2_reg <= icmp_ln88_reg_495;
        icmp_ln88_reg_495_pp0_iter3_reg <= icmp_ln88_reg_495_pp0_iter2_reg;
        icmp_ln88_reg_495_pp0_iter4_reg <= icmp_ln88_reg_495_pp0_iter3_reg;
        icmp_ln88_reg_495_pp0_iter5_reg <= icmp_ln88_reg_495_pp0_iter4_reg;
        icmp_ln88_reg_495_pp0_iter6_reg <= icmp_ln88_reg_495_pp0_iter5_reg;
        icmp_ln88_reg_495_pp0_iter7_reg <= icmp_ln88_reg_495_pp0_iter6_reg;
        icmp_ln88_reg_495_pp0_iter8_reg <= icmp_ln88_reg_495_pp0_iter7_reg;
        icmp_ln88_reg_495_pp0_iter9_reg <= icmp_ln88_reg_495_pp0_iter8_reg;
        icmp_ln90_reg_504_pp0_iter10_reg <= icmp_ln90_reg_504_pp0_iter9_reg;
        icmp_ln90_reg_504_pp0_iter11_reg <= icmp_ln90_reg_504_pp0_iter10_reg;
        icmp_ln90_reg_504_pp0_iter12_reg <= icmp_ln90_reg_504_pp0_iter11_reg;
        icmp_ln90_reg_504_pp0_iter13_reg <= icmp_ln90_reg_504_pp0_iter12_reg;
        icmp_ln90_reg_504_pp0_iter2_reg <= icmp_ln90_reg_504;
        icmp_ln90_reg_504_pp0_iter3_reg <= icmp_ln90_reg_504_pp0_iter2_reg;
        icmp_ln90_reg_504_pp0_iter4_reg <= icmp_ln90_reg_504_pp0_iter3_reg;
        icmp_ln90_reg_504_pp0_iter5_reg <= icmp_ln90_reg_504_pp0_iter4_reg;
        icmp_ln90_reg_504_pp0_iter6_reg <= icmp_ln90_reg_504_pp0_iter5_reg;
        icmp_ln90_reg_504_pp0_iter7_reg <= icmp_ln90_reg_504_pp0_iter6_reg;
        icmp_ln90_reg_504_pp0_iter8_reg <= icmp_ln90_reg_504_pp0_iter7_reg;
        icmp_ln90_reg_504_pp0_iter9_reg <= icmp_ln90_reg_504_pp0_iter8_reg;
        icmp_ln95_reg_508_pp0_iter10_reg <= icmp_ln95_reg_508_pp0_iter9_reg;
        icmp_ln95_reg_508_pp0_iter11_reg <= icmp_ln95_reg_508_pp0_iter10_reg;
        icmp_ln95_reg_508_pp0_iter12_reg <= icmp_ln95_reg_508_pp0_iter11_reg;
        icmp_ln95_reg_508_pp0_iter2_reg <= icmp_ln95_reg_508;
        icmp_ln95_reg_508_pp0_iter3_reg <= icmp_ln95_reg_508_pp0_iter2_reg;
        icmp_ln95_reg_508_pp0_iter4_reg <= icmp_ln95_reg_508_pp0_iter3_reg;
        icmp_ln95_reg_508_pp0_iter5_reg <= icmp_ln95_reg_508_pp0_iter4_reg;
        icmp_ln95_reg_508_pp0_iter6_reg <= icmp_ln95_reg_508_pp0_iter5_reg;
        icmp_ln95_reg_508_pp0_iter7_reg <= icmp_ln95_reg_508_pp0_iter6_reg;
        icmp_ln95_reg_508_pp0_iter8_reg <= icmp_ln95_reg_508_pp0_iter7_reg;
        icmp_ln95_reg_508_pp0_iter9_reg <= icmp_ln95_reg_508_pp0_iter8_reg;
        select_ln88_reg_499_pp0_iter10_reg <= select_ln88_reg_499_pp0_iter9_reg;
        select_ln88_reg_499_pp0_iter11_reg <= select_ln88_reg_499_pp0_iter10_reg;
        select_ln88_reg_499_pp0_iter12_reg <= select_ln88_reg_499_pp0_iter11_reg;
        select_ln88_reg_499_pp0_iter2_reg <= select_ln88_reg_499;
        select_ln88_reg_499_pp0_iter3_reg <= select_ln88_reg_499_pp0_iter2_reg;
        select_ln88_reg_499_pp0_iter4_reg <= select_ln88_reg_499_pp0_iter3_reg;
        select_ln88_reg_499_pp0_iter5_reg <= select_ln88_reg_499_pp0_iter4_reg;
        select_ln88_reg_499_pp0_iter6_reg <= select_ln88_reg_499_pp0_iter5_reg;
        select_ln88_reg_499_pp0_iter7_reg <= select_ln88_reg_499_pp0_iter6_reg;
        select_ln88_reg_499_pp0_iter8_reg <= select_ln88_reg_499_pp0_iter7_reg;
        select_ln88_reg_499_pp0_iter9_reg <= select_ln88_reg_499_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        icmp_ln88_reg_495 <= icmp_ln88_fu_240_p2;
        select_ln63_cast_reg_490[6 : 0] <= select_ln63_cast_fu_208_p1[6 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter10_storemerge_reg_196 <= ap_phi_reg_pp0_iter9_storemerge_reg_196;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter11_storemerge_reg_196 <= ap_phi_reg_pp0_iter10_storemerge_reg_196;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter12_storemerge_reg_196 <= ap_phi_reg_pp0_iter11_storemerge_reg_196;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter13_storemerge_reg_196 <= ap_phi_reg_pp0_iter12_storemerge_reg_196;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter14_storemerge_reg_196 <= ap_phi_reg_pp0_iter13_storemerge_reg_196;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_storemerge_reg_196 <= ap_phi_reg_pp0_iter0_storemerge_reg_196;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter3_storemerge_reg_196 <= ap_phi_reg_pp0_iter2_storemerge_reg_196;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter4_storemerge_reg_196 <= ap_phi_reg_pp0_iter3_storemerge_reg_196;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter5_storemerge_reg_196 <= ap_phi_reg_pp0_iter4_storemerge_reg_196;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter6_storemerge_reg_196 <= ap_phi_reg_pp0_iter5_storemerge_reg_196;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter7_storemerge_reg_196 <= ap_phi_reg_pp0_iter6_storemerge_reg_196;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter8_storemerge_reg_196 <= ap_phi_reg_pp0_iter7_storemerge_reg_196;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter9_storemerge_reg_196 <= ap_phi_reg_pp0_iter8_storemerge_reg_196;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op94_read_state14 == 1'b1))) begin
        gmem_addr_1_read_reg_541 <= m_axi_gmem_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln90_reg_504_pp0_iter4_reg == 1'd1) & (icmp_ln88_reg_495_pp0_iter4_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        gmem_addr_1_reg_529 <= add_ln91_3_fu_342_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln88_reg_495_pp0_iter12_reg == 1'd0))) begin
        gmem_addr_reg_535 <= add_ln91_1_fu_401_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln88_fu_240_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln90_reg_504 <= icmp_ln90_fu_269_p2;
        icmp_ln95_reg_508 <= icmp_ln95_fu_278_p2;
        select_ln88_reg_499 <= select_ln88_fu_261_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln95_reg_508_pp0_iter3_reg == 1'd1) & (icmp_ln31 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        mul_ln97_reg_524 <= grp_fu_1424_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln31 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        skip_row_arr_load_reg_519 <= skip_row_arr_q0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln88_fu_240_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter19_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln88_reg_495_pp0_iter18_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        dst_counter_4_out_ap_vld = 1'b1;
    end else begin
        dst_counter_4_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (ap_predicate_op77_readreq_state7 == 1'b1))) begin
        gmem_blk_n_AR = m_axi_gmem_ARREADY;
    end else begin
        gmem_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        gmem_blk_n_AW = m_axi_gmem_AWREADY;
    end else begin
        gmem_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter20 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        gmem_blk_n_B = m_axi_gmem_BVALID;
    end else begin
        gmem_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (ap_predicate_op94_read_state14 == 1'b1))) begin
        gmem_blk_n_R = m_axi_gmem_RVALID;
    end else begin
        gmem_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter15 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        gmem_blk_n_W = m_axi_gmem_WREADY;
    end else begin
        gmem_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_324_ce = 1'b1;
    end else begin
        grp_fu_324_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op77_readreq_state7 == 1'b1))) begin
        m_axi_gmem_ARVALID = 1'b1;
    end else begin
        m_axi_gmem_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_gmem_AWVALID = 1'b1;
    end else begin
        m_axi_gmem_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter20 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_gmem_BREADY = 1'b1;
    end else begin
        m_axi_gmem_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op94_read_state14 == 1'b1))) begin
        m_axi_gmem_RREADY = 1'b1;
    end else begin
        m_axi_gmem_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter15 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_gmem_WVALID = 1'b1;
    end else begin
        m_axi_gmem_WVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        skip_row_arr_ce0 = 1'b1;
    end else begin
        skip_row_arr_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln88_fu_246_p2 = (indvar_flatten98_fu_114 + 13'd1);

assign add_ln91_1_fu_401_p2 = (zext_ln91_fu_397_p1 + dst_buff);

assign add_ln91_2_fu_332_p2 = (src_counter_fu_106 + 32'd10);

assign add_ln91_3_fu_342_p2 = (zext_ln91_1_fu_338_p1 + src_buff);

assign add_ln91_fu_391_p2 = (j_1_cast_fu_388_p1 + dst_counter_fu_102);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter20 == 1'b1) & (m_axi_gmem_BVALID == 1'b0)) | ((ap_enable_reg_pp0_iter13 == 1'b1) & (ap_predicate_op94_read_state14 == 1'b1) & (m_axi_gmem_RVALID == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter20 == 1'b1) & (m_axi_gmem_BVALID == 1'b0)) | ((ap_enable_reg_pp0_iter15 == 1'b1) & (m_axi_gmem_WREADY == 1'b0)) | ((m_axi_gmem_AWREADY == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b1)) | ((ap_enable_reg_pp0_iter13 == 1'b1) & (ap_predicate_op94_read_state14 == 1'b1) & (m_axi_gmem_RVALID == 1'b0)) | ((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_block_state7_io)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter20 == 1'b1) & (m_axi_gmem_BVALID == 1'b0)) | ((ap_enable_reg_pp0_iter15 == 1'b1) & (m_axi_gmem_WREADY == 1'b0)) | ((m_axi_gmem_AWREADY == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b1)) | ((ap_enable_reg_pp0_iter13 == 1'b1) & (ap_predicate_op94_read_state14 == 1'b1) & (m_axi_gmem_RVALID == 1'b0)) | ((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_block_state7_io)));
end

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state14_pp0_stage0_iter13 = ((ap_predicate_op94_read_state14 == 1'b1) & (m_axi_gmem_RVALID == 1'b0));
end

assign ap_block_state15_pp0_stage0_iter14 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage0_iter15 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter16 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage0_iter17 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage0_iter18 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage0_iter19 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state21_pp0_stage0_iter20 = (m_axi_gmem_BVALID == 1'b0);
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state7_io = ((ap_predicate_op77_readreq_state7 == 1'b1) & (m_axi_gmem_ARREADY == 1'b0));
end

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_425 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign ap_phi_reg_pp0_iter0_storemerge_reg_196 = 'bx;

always @ (*) begin
    ap_predicate_op77_readreq_state7 = ((icmp_ln90_reg_504_pp0_iter5_reg == 1'd1) & (icmp_ln88_reg_495_pp0_iter5_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op94_read_state14 = ((icmp_ln90_reg_504_pp0_iter12_reg == 1'd1) & (icmp_ln88_reg_495_pp0_iter12_reg == 1'd0));
end

assign counter_2_fu_289_p2 = (counter_fu_110 + 32'd1);

assign counter_3_fu_295_p3 = ((icmp_ln95_fu_278_p2[0:0] == 1'b1) ? counter_2_fu_289_p2 : counter_fu_110);

assign dst_counter_2_fu_415_p2 = (dst_counter_fu_102 + 32'd8);

assign dst_counter_3_fu_421_p3 = ((icmp_ln95_reg_508_pp0_iter12_reg[0:0] == 1'b1) ? dst_counter_2_fu_415_p2 : dst_counter_fu_102);

assign dst_counter_4_out = dst_counter_fu_102;

assign grp_fu_1424_p_ce = grp_fu_324_ce;

assign grp_fu_1424_p_din0 = skip_row_arr_load_reg_519;

assign grp_fu_1424_p_din1 = 32'd11;

assign icmp_ln88_fu_240_p2 = ((indvar_flatten98_fu_114 == 13'd8000) ? 1'b1 : 1'b0);

assign icmp_ln89_fu_255_p2 = ((j_fu_98 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln90_fu_269_p2 = ((select_ln88_fu_261_p3 == 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln95_fu_278_p2 = ((select_ln88_fu_261_p3 == 4'd7) ? 1'b1 : 1'b0);

assign j_1_cast_fu_388_p1 = select_ln88_reg_499_pp0_iter12_reg;

assign j_1_fu_303_p2 = (select_ln88_fu_261_p3 + 4'd1);

assign m_axi_gmem_ARADDR = gmem_addr_1_reg_529;

assign m_axi_gmem_ARBURST = 2'd0;

assign m_axi_gmem_ARCACHE = 4'd0;

assign m_axi_gmem_ARID = 1'd0;

assign m_axi_gmem_ARLEN = 32'd1;

assign m_axi_gmem_ARLOCK = 2'd0;

assign m_axi_gmem_ARPROT = 3'd0;

assign m_axi_gmem_ARQOS = 4'd0;

assign m_axi_gmem_ARREGION = 4'd0;

assign m_axi_gmem_ARSIZE = 3'd0;

assign m_axi_gmem_ARUSER = 1'd0;

assign m_axi_gmem_AWADDR = gmem_addr_reg_535;

assign m_axi_gmem_AWBURST = 2'd0;

assign m_axi_gmem_AWCACHE = 4'd0;

assign m_axi_gmem_AWID = 1'd0;

assign m_axi_gmem_AWLEN = 32'd1;

assign m_axi_gmem_AWLOCK = 2'd0;

assign m_axi_gmem_AWPROT = 3'd0;

assign m_axi_gmem_AWQOS = 4'd0;

assign m_axi_gmem_AWREGION = 4'd0;

assign m_axi_gmem_AWSIZE = 3'd0;

assign m_axi_gmem_AWUSER = 1'd0;

assign m_axi_gmem_WDATA = ap_phi_reg_pp0_iter15_storemerge_reg_196;

assign m_axi_gmem_WID = 1'd0;

assign m_axi_gmem_WLAST = 1'b0;

assign m_axi_gmem_WSTRB = 1'd1;

assign m_axi_gmem_WUSER = 1'd0;

assign select_ln63_cast_fu_208_p1 = select_ln63;

assign select_ln88_fu_261_p3 = ((icmp_ln89_fu_255_p2[0:0] == 1'b1) ? 4'd0 : j_fu_98);

assign skip_row_arr_address0 = zext_ln97_fu_284_p1;

assign src_counter_2_fu_356_p2 = (mul_ln97_reg_524 + src_counter_fu_106);

assign src_counter_3_fu_361_p3 = ((icmp_ln31[0:0] == 1'b1) ? src_counter_2_fu_356_p2 : src_counter_fu_106);

assign src_counter_4_fu_368_p2 = (src_counter_3_fu_361_p3 + select_ln63_cast_reg_490);

assign src_counter_5_fu_373_p3 = ((icmp_ln95_reg_508_pp0_iter4_reg[0:0] == 1'b1) ? src_counter_4_fu_368_p2 : src_counter_fu_106);

assign zext_ln91_1_fu_338_p1 = add_ln91_2_fu_332_p2;

assign zext_ln91_fu_397_p1 = add_ln91_fu_391_p2;

assign zext_ln97_fu_284_p1 = counter_fu_110;

always @ (posedge ap_clk) begin
    select_ln63_cast_reg_490[31:7] <= 25'b0000000000000000000000000;
end

endmodule //dut_dut_Pipeline_VITIS_LOOP_88_5_VITIS_LOOP_89_6
